# Generated by Django 5.1.1 on 2024-10-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MeteorologicalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variable", models.CharField(max_length=50)),
                ("resolution", models.IntegerField()),
                ("json_path", models.FilePathField(path="path/a/json/directory")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
